### ISSUE TITLE
Existing Public IP vs FW Public IP

### ISSUE THREAD

**Issue by giovannifl** [Azure/terraform-azurerm-avm-res-network-azurefirewall#10]
Hello,
Looking to this module documentation and while trying to deploy a FW (AZFW_VNet mode), it seems these parameters are all required:

- public_ip_location 
- public_ip_resource_group_name 
- public_ip_allocation_method 
- public_ip_name

However, it is also possible to configure a "firewall_ip_configuration" : 

```
 firewall_ip_configuration = [{
    name = "default"
    public_ip_address_id = "${module.fw-pip.public_ip_id}"
    subnet_id            = module.vnet.subnets.AzureFirewallSubnet.id
  }]
```

In my case, I want to deploy a new FW in an existing subnet so I need to configure the  **firewall_ip_configuration** section. Right ?

If this is the case, then I may also want attach an existing Public IP to the FW.

If I do that (meaning configuring firewall_ip_configuration with a public_ip_address_id and a subnet_id ) in addition to also creating a Public IP with the other variables (i.e. public_ip_name ) , what will happen is that the FW will be attached to existing Public IP and the new Public IP, created with the public_ip_name will not be used at all.

However if I don't  provide public_ip_location, public_ip_resource_group_name, public_ip_allocation_method and public_ip_name Terraform will complain because these vars are required.

Please could you confirm if and how this module should be called to deploy a FW into an existing subnet, without wasting Public IPs ?

Thanks,
Giovanni

**Comment by cshea-msft** [comment]
@giovannifl a new version has been released where the Public IP built into the module has been removed. So those parameters are no longer required. You must create your own Public IP resource or use one already created. If you use an existing subnet, make sure you use the correct configuration for the Firewall subnet.
