### ISSUE TITLE
[AVM Module Issue]: Add Private IP Address to the outputs

### ISSUE THREAD

**Issue by jrspinella** [Azure/terraform-azurerm-avm-res-network-azurefirewall#20]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Feature Request

### Description

As part of the FW configuration, we use FW private IP address in a Hub/Spoke model for force tunneling.

**Comment by cshea-msft** [comment]
Hopefully to push PR in the next week.

**Comment by cshea-msft** [comment]
PR as been published
