### ISSUE TITLE
[AVM Module Issue]: Log analytics workspace not enabled by default

### ISSUE THREAD

**Issue by maurojasmsft** [Azure/terraform-azurerm-avm-res-network-azurefirewall#25]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Diagnostic settings is not required by default. This is required to comply with https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#monitor-azure-firewall-metrics

variable "diagnostic_settings" {
  type = map(object({
    name                                     = optional(string, null)
    log_categories                           = optional(set(string), [])
    log_groups                               = optional(set(string), ["allLogs"])
    metric_categories                        = optional(set(string), ["AllMetrics"])
    log_analytics_destination_type           = optional(string, "Dedicated")
    workspace_resource_id                    = optional(string, null)
    storage_account_resource_id              = optional(string, null)
    event_hub_authorization_rule_resource_id = optional(string, null)
    event_hub_name                           = optional(string, null)
    marketplace_partner_resource_id          = optional(string, null)
  }))
  default  = {}
  nullable = false

**Comment by cshea-msft** [comment]
@maurojasmsft Diagnostics settings is set to false for nullable. I will create an example to show setting up monitoring for the Azure firewall. That should meet the requirements. The Diagnostic Settings variable is also part of the templates from the AVM team so following that guidance.
