### ISSUE TITLE
[AVM Module Issue]: Apply DDoS protection on the Firewall Vnet

### ISSUE THREAD

**Issue by maurojasmsft** [Azure/terraform-azurerm-avm-res-network-azurefirewall#27]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Build code to apply DDoS on the Firewall Vnet per APRL 

https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#configure-ddos-protection-on-the-azure-firewall-vnet

**Comment by cshea-msft** [comment]
@maurojasmsft This should be on in the vnet module. There is no DDoS option for firewall. this is a firewall resource modul.e
