### ISSUE TITLE
[AVM Module Issue]: Firewall Policies not associated to the examples

### ISSUE THREAD

**Issue by maurojasmsft** [Azure/terraform-azurerm-avm-res-network-azurefirewall#28]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Per https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#leverage-azure-policy-inheritance-model, we need to have some sort of firewall policy to allow/deny traffic and associate to a given firewall. Can this be built?

**Comment by cshea-msft** [comment]
this is a Firewall Policy recommendation. There is a an example for it in that module.
