### ISSUE TITLE
How does one reference the public ip address id?

### ISSUE THREAD

**Issue by thufael-tech** [Azure/terraform-azurerm-avm-res-network-azurefirewall#8]
Appreciate this is the first release under v0.1.0 and possibly my lack of insight, wondering how does one associate the Public IP Address ID that is created by the AVM module? The reference template does not associate the public IP address or the subnet.

There is no output value for this.

Under the main.tf, we have the following

```
module "avm-res-network-azurefirewall" {
  source  = "Azure/avm-res-network-azurefirewall/azurerm"
  version = "0.1.0"

  name                          = module.naming_style.firewall.name
  location                      = var.primary_location
  resource_group_name           = "${module.naming_style.resource_group.name}-connectivity"
  firewall_sku_tier             = var.firewall_config.default.sku_tier
  firewall_sku_name             = var.firewall_config.default.sku_name
  public_ip_location            = var.primary_location
  public_ip_name                = "${module.naming_style.firewall.name}-pip"
  public_ip_resource_group_name = "${module.naming_style.resource_group.name}-connectivity"
  firewall_ip_configuration = [{
    name                 = module.naming_style.firewall_ip_configuration.name
    public_ip_address_id = **what goes here if no output?**
    subnet_id            = module.avm-res-network-virtualnetwork.subnets["AzureFirewallSubnet"].id
  }]
}
```

**Comment by cshea-msft** [comment]
Thank you for the feedback @thufael-tech currently rolling out a change to the module. The PIP will be created in the example root module and not in the main.tf file.

**Comment by cshea-msft** [comment]
@thufael-tech new version is available. PIP has been removed from the module. If you need Public IP you can create it seperately from this module. thanks for the feedback!
